# $FreeBSD$

freebsd_instance:
  image: freebsd-12-2-release-amd64
  cpu: 8
  memory: 24G

env:
  CIRRUS_CLONE_DEPTH: 1

task:
  timeout_in: 120m
  install_script:
  - pkg install -y poudriere bash git-lite
  script:
  - bash ci/setup-jail.sh
  test_script:
  - bash ci/test-ports.sh
